development:
  adapter: postgresql
  encoding: unicode
  database: pilgrim_logger
  pool: 2
  username: pilgrim_logger
  password: pilgrim_logger
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
